In [18]:
import os

from arcgis.gis import GIS
from arcgis.geoenrichment import get_countries, Country
from dotenv import find_dotenv, load_dotenv

In [19]:
load_dotenv(find_dotenv())

gis = GIS(
    url=os.getenv('ESRI_GIS_URL'), 
    username=os.getenv('ESRI_GIS_USERNAME'),
    password=os.getenv('ESRI_GIS_PASSWORD')
)

gis

GIS @ https://bateam.maps.arcgis.com version:9.2

In [22]:
get_countries(as_df=True, gis=GIS('pro'))

  iso2 iso3   country_name  vintage     country_id        data_source_id
0   CA  CAN         Canada     2020  CAN_ESRI_2019  LOCAL;;CAN_ESRI_2019
1   JP  JPN          Japan     2020      JAPAN2020      LOCAL;;JAPAN2020
2   US  USA  United States     2019  USA_ESRI_2019  LOCAL;;USA_ESRI_2019
3   US  USA  United States     2020  USA_ESRI_2020  LOCAL;;USA_ESRI_2020
4   US  USA  United States     2021  USA_ESRI_2021  LOCAL;;USA_ESRI_2021

In [24]:
cntry = Country('USA', gis=GIS('pro'), year=2019)

cntry

In [25]:
ev = cntry.enrich_variables

print(ev.info())
ev.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16911 entries, 0 to 16910
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               16911 non-null  object
 1   alias              16911 non-null  object
 2   data_collection    16911 non-null  object
 3   enrich_name        16911 non-null  object
 4   enrich_field_name  16911 non-null  object
dtypes: object(5)
memory usage: 660.7+ KB
None

,name,alias,data_collection,enrich_name,enrich_field_name
0,CHILD_CY,2019 Child Population,AgeDependency,AgeDependency.CHILD_CY,AgeDependency_CHILD_CY
1,WORKAGE_CY,2019 Working-age Population,AgeDependency,AgeDependency.WORKAGE_CY,AgeDependency_WORKAGE_CY
2,SENIOR_CY,2019 Senior Population,AgeDependency,AgeDependency.SENIOR_CY,AgeDependency_SENIOR_CY
3,CHLDDEP_CY,2019 Child Dependency Ratio,AgeDependency,AgeDependency.CHLDDEP_CY,AgeDependency_CHLDDEP_CY
4,AGEDEP_CY,2019 Age Dependency Ratio,AgeDependency,AgeDependency.AGEDEP_CY,AgeDependency_AGEDEP_CY

In [26]:
kv = ev[
    (ev.data_collection.str.lower().str.contains('key'))
    & (ev.name.str.endswith('CY'))
].drop_duplicates('name').reset_index(drop=True)

kv

,name,alias,data_collection,enrich_name,enrich_field_name
0,TOTPOP_CY,2019 Total Population,KeyUSFacts,KeyUSFacts.TOTPOP_CY,KeyUSFacts_TOTPOP_CY
1,GQPOP_CY,2019 Population in Group Quarters,KeyUSFacts,KeyUSFacts.GQPOP_CY,KeyUSFacts_GQPOP_CY
2,DIVINDX_CY,2019 Diversity Index,KeyUSFacts,KeyUSFacts.DIVINDX_CY,KeyUSFacts_DIVINDX_CY
3,TOTHH_CY,2019 Total Households,KeyUSFacts,KeyUSFacts.TOTHH_CY,KeyUSFacts_TOTHH_CY
4,AVGHHSZ_CY,2019 Average Household Size,KeyUSFacts,KeyUSFacts.AVGHHSZ_CY,KeyUSFacts_AVGHHSZ_CY
5,MEDHINC_CY,2019 Median Household Income,KeyUSFacts,KeyUSFacts.MEDHINC_CY,KeyUSFacts_MEDHINC_CY
6,AVGHINC_CY,2019 Average Household Income,KeyUSFacts,KeyUSFacts.AVGHINC_CY,KeyUSFacts_AVGHINC_CY
7,PCI_CY,2019 Per Capita Income,KeyUSFacts,KeyUSFacts.PCI_CY,KeyUSFacts_PCI_CY
8,TOTHU_CY,2019 Total Housing Units,KeyUSFacts,KeyUSFacts.TOTHU_CY,KeyUSFacts_TOTHU_CY
9,OWNER_CY,2019 Owner Occupied HUs,KeyUSFacts,KeyUSFacts.OWNER_CY,KeyUSFacts_OWNER_CY
10,RENTER_CY,2019 Renter Occupied HUs,KeyUSFacts,KeyUSFacts.RENTER_CY,KeyUSFacts_RENTER_CY
11,VACANT_CY,2019 Vacant Housing Units,KeyUSFacts,KeyUSFacts.VACANT_CY,KeyUSFacts_VACANT_CY
12,MEDVAL_CY,2019 Median Home Value,KeyUSFacts,KeyUSFacts.MEDVAL_CY,KeyUSFacts_MEDVAL_CY
13,AVGVAL_CY,2019 Average Home Value,KeyUSFacts,KeyUSFacts.AVGVAL_CY,KeyUSFacts_AVGVAL_CY
14,POPGRW10CY,2010-2019 Growth Rate: Population,KeyUSFacts,KeyUSFacts.POPGRW10CY,KeyUSFacts_POPGRW10CY
15,HHGRW10CY,2010-2019 Growth Rate: Households,KeyUSFacts,KeyUSFacts.HHGRW10CY,KeyUSFacts_HHGRW10CY
16,FAMGRW10CY,2010-2019 Growth Rate: Families,KeyUSFacts,KeyUSFacts.FAMGRW10CY,KeyUSFacts_FAMGRW10CY
17,DPOP_CY,2019 Total Daytime Population,KeyUSFacts,KeyUSFacts.DPOP_CY,KeyUSFacts_DPOP_CY
18,DPOPWRK_CY,2019 Daytime Pop: Workers,KeyUSFacts,KeyUSFacts.DPOPWRK_CY,KeyUSFacts_DPOPWRK_CY
19,DPOPRES_CY,2019 Daytime Pop: Residents,KeyUSFacts,KeyUSFacts.DPOPRES_CY,KeyUSFacts_DPOPRES_CY